services:
  backend:
    build:
      context: D:\financeiro
      dockerfile: ./docker-back/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: Host=db;Database=financeiro_db;Username=iarlon_admin;Password=ec867106c8f0d288d67a4ca2b7a15dd3
      Jwt__Key: 270f493790fd995fe3cb709d309102b413e9ee909b5259bbb925907a0173f5d0918dd39fa8f18ed061c4e0ef10a40028a2ff5ef0a181fb06d5088709039bd8a3
    ports:
      - "8080:8080"

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: financeiro_db
      POSTGRES_USER: iarlon_admin
      POSTGRES_PASSWORD: ec867106c8f0d288d67a4ca2b7a15dd3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iarlon_admin -d financeiro_db"]
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
  sonar_data:
  sonar_logs: